services:
  individuals-api:
    build:
      context: ./individuals-api
    container_name: individuals-api
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      keycloak:
        condition: service_healthy
      loki:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      nexus:
        condition: service_healthy
      person-service:
        condition: service_healthy
      tempo:
        condition: service_started
    healthcheck:
      test: [ "CMD","wget","--spider","localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_system_network

  keycloak:
    image: "quay.io/keycloak/keycloak:26.2"
    container_name: "individuals-keycloak"
    command: start-dev --import-realm --health-enabled=true
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8080:8080"
    volumes:
      - ./infrastructure/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", 'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_system_network

  keycloak-postgres:
    image: postgres:17
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_system_network

  alloy:
    container_name: alloy
    image: grafana/alloy:v1.10.2
    ports:
      - "12345:12345"
    command: run --storage.path=/var/lib/alloy/data --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock.raw:/var/run/docker.sock
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - payment_system_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_system_network

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: --config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infrastructure/loki/local-config.yaml:/etc/loki/local-config.yaml
    healthcheck:
      test: [ "CMD", "wget","--spider", "http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_system_network

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_started
      alloy:
        condition: service_started
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/dashboards
    healthcheck:
      test: [ "CMD","wget","--spider","http://localhost:3000/api/heatlh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_system_network

  tempo:
    image: grafana/tempo:main-d1ec3c6
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"
      - "4318:4318"
    volumes:
      - ./infrastructure/tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - payment_system_network

  nexus:
    # image: sonatype/nexus3:3.85.0 
    image: sonatype/nexus3:3.76.0
    container_name: nexus
    ports:
      - "8800:8081"
    environment:
      NEXUS_SECURITY_INITIAL_PASSWORD: admin
      NEXUS_SECURITY_RANDOMPASSWORD: false
    healthcheck:
      test: [ "CMD","curl","-I","http://localhost:8081/service/rest/v1/status" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - payment_system_network

  person-service:
    build:
      context: ./person-service
    container_name: person-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD","wget","--spider","localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      person-db:
        condition: service_healthy
    networks:
      - payment_system_network

  person-db:
    image: postgres:17
    container_name: person-db
    environment:
      POSTGRES_DB: person
      POSTGRES_USER: personadmin
      POSTGRES_PASSWORD: personadmin
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d person -U personadmin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - payment_system_network

networks:
  payment_system_network:
    driver: bridge
#  axon-server:
#    image: axoniq/axonserver:2025.2.0-nonroot
#    container_name: axon
#    ports:
#      - "8024:8024"
#      - "8124:8124"
#    healthcheck:
#      test: ["CMD", "curl","-f", "http://localhost:8024/actuator/health"]
#      interval: 10s
#      timeout: 5s
#      retries: 5