server:
  port: 8084

spring:
  application:
    name: currency-rate-service
  datasource:
    url: jdbc:postgresql://${CURRENCY-RATE-SERVICE_DB_HOST}:${CURRENCY-RATE-SERVICE_DB_PORT}/currencyrate
    username: ${CURRENCY-RATE-SERVICE_DB_USERNAME}
    password: ${CURRENCY-RATE-SERVICE_DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${CURRENCY-RATE-SERVICE_DB_HOST}:${CURRENCY-RATE-SERVICE_DB_PORT}/currencyrate
    user: ${CURRENCY-RATE-SERVICE_DB_USERNAME}
    password: ${CURRENCY-RATE-SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
        generate_statistics: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/payment/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_URL}/v1/traces

currency-rate-service:
  provider:
    currate:
      api-key: ${CURRATE_API_KEY}
      base-url: https://currate.ru
      code: cur
      name: currate
      description: first currency provider
      priority: 1

