apiVersion: 1

prune: true

datasources:
  - name: loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - matcherRegex: '"traceId":"(\w+)"'
          name: traceID
          url: '$${__value.raw}'

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      timeInterval: 10s

  - name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-5s'
        spanEndTimeShift: '5s'
        tags: [{ key: 'service.name', value: 'container_name' }]
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false