apiVersion: 1

prune: true

datasources:
  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      timeInterval: 10s