upstream currency-rate {
    server currency-rate-service-1:8084;
    server currency-rate-service-2:8084;
    server currency-rate-service-3:8084;
}
server {
    location / {
        proxy_pass http://currency-rate;
    }
}

