@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(dev, "External Client")

System_Boundary(indSystem,"Individuals Auth System"){
    Container(indApi,"Individuals API","Spring Boot WebFlux","Http-запросы (логин, получение токена, /me)","JSON/REST")
    Container(keycloak, "Keycloak", "Keycloak 24","Управление пользователями")
    Container(keycloakPs, "Keycloak Postgres","PostgreSQL", "Хранение пользователей Keycloak")
    Container(prometheus, "Prometheus","Monitoring","Сбор метрик сервисов")
    Container(loki, "Loki", "Grafana Loki","Сбор логов сервисов")
    Container(grafana,"Grafana","Grafana","Визуализация метрик и логов")
}

Rel(dev,indApi, "Http-запросы (регистрация, логин, /me)", "JSON/REST")
Rel(indApi,keycloak, "Rest запросы в Keycloak","HTTP")
Rel(keycloak, keycloakPs, "JDBC","SQL")
Rel(indApi,loki,"Logging","stdout->Docker->Loki")
Rel(indApi, prometheus, "Отправка Метрик", "Micrometer")
Rel(grafana,prometheus, "Визуализация метрик")
Rel(grafana,loki, "Визуализация логов")

@enduml