@startuml
actor Client
participant API
participant Keycloak

Client -> API: POST /api/v1/registration
API -> Keycloak: Create User
Keycloak -> API: OK
API -> Keycloak: RequestToken
Keycloak -> API: access_token, refresh_token
API -> Client: tokens
@enduml
