@startuml
actor Client
participant IndividualsAPI
participant TransactionService
database DB
queue Kafka

== Init ==
Client -> IndividualsAPI: POST /api/v1/transactions/init (type=deposit)
IndividualsAPI -> TransactionService: POST /api/v1/transactions/init (type=deposit)
TransactionService -> TransactionService: Проверка кошелька
alt Пополнение возможно
    TransactionService --> IndividualsAPI: TransactionInitResponse
    IndividualsAPI --> Client: TransactionInitResponse
else Пополнение невозможно
    TransactionService --> IndividualsAPI: ErrorResponse
    IndividualsAPI --> Client: ErrorResponse
end
== Confirm ==
Client -> IndividualsAPI: POST /api/v1/transactions/confirm (type=deposit)
IndividualsAPI -> TransactionService: POST /api/v1/transactions/confirm (type=deposit)
TransactionService -> TransactionService: Проверка кошелька
alt Пополнение невозможно
    TransactionService --> IndividualsAPI: ErrorResponse
    IndividualsAPI --> Client: ErrorResponse
end

group transaction
    TransactionService -> Kafka: TransactionCreatedEvent
    TransactionService -> DB: Создать транзакцию PENDING
end
  TransactionService --> IndividualsAPI: TransactionConfirmResponse
IndividualsAPI --> Client: TransactionConfirmResponse
Kafka -> TransactionService: TransactionCompletedEvent (async)
TransactionService -> TransactionService: Зачислить средства
group transaction
    TransactionService -> DB: Баланс++
    TransactionService -> DB: Статус транзакции COMPLETED
end
@enduml