@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(fakePaymentProviderContainer,"Fake Payment Provider","Spring boot")

Component(transactionController, "Transaction Controller", "Rest Controller", "Получение и создание транзакций пополнения")
Component(payoutController, "Payout Controller", "Rest Controller", "Получение и создание транзакций выплат")
Component(webhookController, "Webhook Controller", "Rest Controller", "Получение вебхуков транзакций")

Component(transactionService, "Transaction Service","Сервис","Обработка транзакций пополнения")
Component(payoutService, "Payout Service", "Сервис", "Обработка транзакций выплат")
Component(webhookService, "Webhook Service","Сервис", "Обработка вебхуков")
Component(merchantService, "Merchant Service", "Сервис", "Аутентификация пользователей")

Component(transactionRepository, "Transaction Repository", "Репозиторий", "Хранилище транзакций пополнения")
Component(payoutRepository, "Payout Repository", "Репозиторий", "Хранилище транзакций выплат")
Component(webhookRepository, "Webhook Repository", "Репозиторий", "Аудит вебхуков")
Component(merchantRepository, "Merchant Repository", "Репозиторий", "Хранилище пользователей")


Component(transactionDto, "Transaction Dto", "Сгенерированные DTO")
Component(payoutDto, "Payout Dto", "Сгенерированные DTO")
Component(webhookDto, "Webhook Dto", "Сгенерированные DTO")

Lay_R(fakePaymentProviderContainer, transactionController)
Lay_R(transactionController, payoutController)
Lay_R(payoutController, webhookController)

Rel_D(transactionController,transactionService, "вызов")
Rel_D(payoutController,payoutService, "вызов")
Rel_D(webhookController,webhookService, "вызов")

Rel(webhookService,payoutService, "вызов")
Rel(webhookService,transactionService, "вызов")

Rel_D(transactionService, merchantService, "Вызов")
Rel_D(payoutService, merchantService, "Вызов")

Rel_D(transactionService,transactionRepository, "вызов")
Rel_D(payoutService,payoutRepository, "вызов")
Rel_D(webhookService,webhookRepository, "вызов")
Rel_D(merchantService, merchantRepository, "вызов")

Rel_U(transactionController, transactionDto, "использует")
Rel_U(payoutController, payoutDto, "использует")
Rel_U(webhookController, webhookDto, "использует")
@enduml