@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(indApi,"person-service","Spring boot")

Component(indController, "IndividualController", "Rest Controller", "Обрабатывает запросы individuals-api")
Component(indService,"IndividualService","Сервис","Создание, обновление, удаление пользователей")
Component(indRepository, "Individual Repository", "Хранение пользователй")
Component(indRepositoryAudit,"IndividualsRepositoryAudit", "Аудит для Individuals Repository")
Component(personDto, "DTO (сгенерированные)", "DTO для взаимодействия с Person Service")

Rel(indController, indService, "вызов")
Rel(indController, personDto, "использует")
Rel(indService, indRepository, "вызов")
Rel(indRepository, indRepositoryAudit, "использует")

@enduml