@startuml
actor Client
participant IndividualsApi
participant PersonService
participant Keycloak

Client -> IndividualsApi: POST /api/v1/registration
IndividualsApi -> PersonService: POST /api/v1/users
alt PersonService user created
    PersonService -> IndividualsApi: created, userId
    IndividualsApi -> Keycloak: Create Keycloak User(userId)

    alt Keycloak success
        Keycloak -> IndividualsApi: OK
        IndividualsApi -> Keycloak: RequestToken
        Keycloak -> IndividualsApi: access_token, refresh_token
        IndividualsApi -> Client: tokens
    else Keycloak exception
        Keycloak -> IndividualsApi: exception
        IndividualsApi -> PersonService: DELETE /api/v1/users/userId
        PersonService -> IndividualsApi: 204
        IndividualsApi -> Client: ErrorResponse
    end

else PersonService exception
    PersonService -> IndividualsApi: exception
    IndividualsApi -> Client: ErrorResponse
end
@enduml