@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(ts,"Transaction-service","Spring boot")

Component(tsController, "Transaction Controller", "Rest Controller", "Обрабатывает запросы individuals-api")
Component(tsService,"Transaction Service","Service","Пополнение, перевод и  вывод денежных средств")
Component(wService, "Wallet Service", "Service", "Операции над кошельками пользователей")
Component(kafka,"Kafka Client","Spring Kafka")

Component(tsRepo, "Transaction Repository","Jpa Repository", "Хранение транзакций")
Component(wRepo, "Wallet Repository", "Jpa Repository","Хранение кошельков")

Component(tsDto, "Transaction Dto", "Сгенерированные ДТО")
Component(kafkaDto, "Kafka Dto", "Kafka ДТО")

Lay_R(ts, tsController)

Rel(tsController, tsService, "вызов")
Rel(tsService, wService, "вызов")

Rel(wService, wRepo, "вызов")
Rel(tsService, tsRepo, "вызов")

Rel_R(kafka, kafkaDto, "использует")
Rel_R(tsController, tsDto, "использует")

BiRel_R(tsService, kafka,"produce/consume")

@enduml