@startuml
actor Client
participant IndividualsAPI
participant CurrencyRateService
database CurrencyRateServiceDB
participant TransactionService
database TransactionServiceDB

== Init ==
Client -> IndividualsAPI: POST /api/v1/transactions/init  (type=transfer)
alt currencyFrom != currencyTo
IndividualsAPI -> CurrencyRateService: GET /api/v1/rates
CurrencyRateService -> CurrencyRateServiceDB: find rate
CurrencyRateServiceDB --> CurrencyRateService: rate
CurrencyRateService --> IndividualsAPI: RateResponse
else rate = 0
end
IndividualsAPI -> TransactionService: POST /api/v1/transactions/init (type=transfer) + rate
TransactionService -> TransactionService: Проверка обоих кошельков
TransactionService -> TransactionService: caclulate fee, validate balances
TransactionService --> IndividualsAPI: TransactionInitResponse
IndividualsAPI --> Client: TransactionInitResponse
== Confirm ==
Client -> IndividualsAPI: POST /api/v1/transactions/confirm (type=transfer)
alt currencyFrom != currencyTo
IndividualsAPI -> CurrencyRateService: GET /api/v1/rates
CurrencyRateService -> CurrencyRateServiceDB: find rate
CurrencyRateServiceDB --> CurrencyRateService: rate
CurrencyRateService --> IndividualsAPI: RateResponse
else rate = 0
end
IndividualsAPI -> TransactionService: POST /api/v1/transactions/confirm (type=transfer) + rate
TransactionService -> TransactionService: Проверка обоих кошельков
TransactionService -> TransactionService: caclulate fee, validate balances
TransactionService -> TransactionService: Debit + Credit
TransactionService -> TransactionServiceDB: Две записи
TransactionService -> TransactionServiceDB: Статус транзакции COMPLETED
TransactionService --> IndividualsAPI: TransactionConfirmResponse
IndividualsAPI --> Client: TransactionConfirmResponse
@enduml