@startuml
actor Client
participant IndividualsAPI
participant TransactionService
database tsDb as "Transaction DB"
participant PaymentService
database psDb as "Payment DB"
participant fpp as "FakePaymentProvider"

queue Kafka

== Init ==

Client -> IndividualsAPI: POST /api/v1/transactions/init (type=withdrawal)
activate IndividualsAPI
    IndividualsAPI -> TransactionService: POST /api/v1/transactions/init (type=withdrawal)
    activate TransactionService
        TransactionService -> TransactionService: Проверка баланса + расчет комиссии
        alt Вывод средств доступен
            TransactionService --> IndividualsAPI: TransactionInitResponse
            IndividualsAPI --> Client: TransactionInitResponse
        else Вывод средств недоступен
            TransactionService --> IndividualsAPI: ErrorResponse
            IndividualsAPI --> Client: ErrorResponse
        end
    deactivate TransactionService
deactivate IndividualsAPI

== Confirm ==

Client -> IndividualsAPI: POST /api/v1/transactions/confirm (type=withdrawal)
activate IndividualsAPI
    IndividualsAPI -> TransactionService: POST /api/v1/transactions/confirm (type=withdrawal)
    activate TransactionService
        TransactionService -> TransactionService: Проверка баланса + расчет комиссии
        break Вывод средств недоступен
            TransactionService --> IndividualsAPI: ErrorResponse
            IndividualsAPI --> Client: ErrorResponse
        end
        TransactionService -> TransactionService: Списать средства
        group transaction
            TransactionService -> tsDb: Баланс--
            TransactionService -> tsDb: Статус транзакции PENDING
                break Transaction DB unavailable
                    TransactionService --> IndividualsAPI: ErrorResponse
                    IndividualsAPI --> Client: ErrorResponse
                end
            TransactionService -> Kafka: TransactionCreatedEvent
        end
        TransactionService --> IndividualsAPI: TransactionConfirmResponse
        IndividualsAPI -> PaymentService: POST /api/v1/payment PaymentRequest type=PAYOUT
        activate PaymentService
            PaymentService -> psDb: insert into payments type=PAYOUT status=FAILED
            psDb --> PaymentService: payment id

                activate fpp
                    alt Payment DB unavailable
                        PaymentService --> IndividualsAPI: ErrorResponse
                        IndividualsAPI -> TransactionService: POST /api/v1/transactions/{transactionId}/compensate
                        TransactionService -> TransactionService: Вернуть средства
                        group transaction
                            TransactionService -> tsDb: баланс++
                            TransactionService -> tsDb: update transaction by id status=FAILED
                            TransactionService -> Kafka: TransactionFailedEvent
                        end
                        TransactionService --> IndividualsAPI: ok
                        IndividualsAPI --> Client: ErrorResponse

                    else Fake Payment Provider return Error
                        PaymentService -> fpp: POST /api/v1/payouts
                        fpp --> PaymentService: ErrorResponse
                        PaymentService -> psDb: update Payout by id status=FAILED
                        PaymentService --> IndividualsAPI: ErrorResponse
                        IndividualsAPI -> TransactionService: POST /api/v1/transactions/{transactionId}/compensate
                        TransactionService -> TransactionService: Вернуть средства
                        group transaction
                            TransactionService -> tsDb: баланс++
                            TransactionService -> tsDb: update transaction by id status=FAILED
                            TransactionService -> Kafka: TransactionFailedEvent
                        end
                        TransactionService --> IndividualsAPI: ok
                        IndividualsAPI --> Client: ErrorResponse
                    else Success
                        PaymentService -> fpp: POST /api/v1/payouts
                        fpp -> fpp: обработка выплаты
                        fpp --> PaymentService: Payout status=PENDING, externalTransactionId
                        PaymentService -> psDb: update payout by id set externalTransactionId
                        psDb --> PaymentService: ok
                        PaymentService --> IndividualsAPI: PaymentResponse type=PAYOUT status=PENDING
                        IndividualsAPI --> Client: TransactionConfirmResponse status=PENDING
                    end
                deactivate fpp
        deactivate PaymentService
    deactivate TransactionService
deactivate IndividualsAPI

== Async later ==

Kafka -> TransactionService: TransactionCompletedEvent
alt completed
    TransactionService -> tsDb: Статус транзакции COMPLETED
else failed
    TransactionService -> TransactionService: Вернуть средства
    group transaction
        TransactionService -> tsDb: Баланс++
        TransactionService -> tsDb: Статус транзакции FAILED
    end
end

@enduml