spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://individuals-keycloak:8080/realms/payment/protocol/openid-connect/certs

management:
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces

individuals-api:
  keycloak:
    baseUrl: http://individuals-keycloak:8080
  person:
    base-url: http://person-service:8082
  transaction:
    base-url: http://transaction-service:8083