spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://individuals-keycloak:8080/realms/payment/protocol/openid-connect/certs

individuals-api:
  keycloak:
    baseUrl: http://individuals-keycloak:8080

individuals:
  url: http://person-service:8082

private:
  url: http://person-service:8082
