server:
  port: 8081

spring:
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/payment/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  observations:
    annotations:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_URL}/v1/traces

individuals-api:
  keycloak:
    baseUrl: ${KEYCLOAK_URL}
    realm: payment
    clientId: individuals-api
    clientSecret: "**********"
  person:
    base-url: ${PERSON_SERVICE_BASE_URL}
  transaction:
    base-url: ${TRANSACTION_SERVICE_BASE_URL}
  currency-rate:
    base-url: ${CURRENCY_RATE_SERVICE_BASE_URL}
logging:
  level:
    com.example: debug