{
 "title": "individuals-api-metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individuals-Api",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"individuals-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Person-Service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"person-service\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction-Service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=\"transaction-service\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individuals-Api CPU usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=\"individuals-api\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Person-Service CPU usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=\"person-service\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction-Service CPU usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_cpu_usage{instance=\"transaction-service\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG time requests",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (uri) (http_server_requests_seconds_sum{instance = \"individuals-api\"}))/ (sum by (uri) (http_server_requests_seconds_count{instance = \"individuals-api\"}))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Requests Counter",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "http_reactive_login_total{instance=\"individuals-api\"}",
       "legendFormat": "login-{{status}}"
      },
      {
       "expr": "http_reactive_registration_total{instance=\"individuals-api\"}",
       "legendFormat": "registration-{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Individuals-api log",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{container_name=\"individuals-api\"}"
      }
     ]
    },
    {
     "title": "Person-Service log",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{container_name=\"person-service\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Person-DB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{instance=\"prometheus.exporter.postgres.psdbs\",datname = \"person\", server = \"person-db:5432\",  __name__=~ \"pg_stat_activity_count\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "{instance=\"prometheus.exporter.postgres.psdbs\",datname = \"person\", server = \"person-db:5432\", __name__=\"pg_stat_activity_max_tx_duration\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Keycloak-DB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{instance=\"prometheus.exporter.postgres.psdbs\",datname = \"keycloak\", server = \"keycloak-postgres:5432\",  __name__=~ \"pg_stat_activity_count\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "{instance=\"prometheus.exporter.postgres.psdbs\",datname = \"keycloak\", server = \"keycloak-postgres:5432\", __name__=\"pg_stat_activity_max_tx_duration\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tracing",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "limit": 20,
     "query": "{.http.url !~ \"/actuator/.*\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}