server:
  port: 8082

spring:
  application:
    name: person-service
  datasource:
    url: jdbc:postgresql://${PERSON_SERVICE_DB_HOST}:${PERSON_SERVICE_DB_PORT}/person
    username: ${PERSON_SERVICE_DB_USERNAME}
    password: ${PERSON_SERVICE_DB_PASSWORD}
    jpa:
      show-sql: true
      generate-ddl: false
  flyway:
    url: jdbc:postgresql://${PERSON_SERVICE_DB_HOST}:${PERSON_SERVICE_DB_PORT}/person
    user: ${PERSON_SERVICE_DB_USERNAME}
    password: ${PERSON_SERVICE_DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/payment/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_URL}/v1/traces