spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://individuals-keycloak:8080/realms/payment/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://person-db:5432/person
    username: personadmin
    password: personadmin
    jpa:
      show-sql: true
      generate-ddl: false
  flyway:
    url: jdbc:postgresql://person-db:5432/person
    user: personadmin
    password: personadmin
